isDestroyed method did return result of a function which did not exist
- when i tried to call isDestroyed I got a TypeError which said that: TypeError: this._isDestroyed is not a function
- isDestroyed now returns the objects _isDestroyed value instead of a function
- test added